# Generated by Django 2.2.6 on 2019-10-24 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encontreiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='nome')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('facebook', models.EmailField(max_length=50, verbose_name='facebook')),
                ('naturalidade', models.CharField(max_length=40, verbose_name='naturalidade')),
                ('cpf', models.CharField(max_length=15, null=True, unique=True, verbose_name='cpf')),
                ('celular', models.CharField(default='', editable=False, max_length=15, verbose_name='celular')),
                ('data_nascimento', models.DateField(null=True, verbose_name='data_nascimento')),
                ('frequentando_igreja', models.CharField(max_length=5, null=True, verbose_name='frequentando_igreja')),
                ('nome_igreja', models.CharField(blank=True, max_length=50, null=True)),
                ('cep', models.CharField(max_length=10, null=True, verbose_name='cep')),
                ('logradouro', models.CharField(max_length=40, null=True, verbose_name='rua')),
                ('numero', models.IntegerField(null=True, verbose_name='numero')),
                ('complemento', models.CharField(max_length=60, null=True, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=25, verbose_name='bairro')),
                ('estado', models.CharField(max_length=4, null=True, verbose_name='estados')),
                ('cidade', models.CharField(max_length=30, null=True, verbose_name='idades')),
                ('local_trabalho', models.CharField(max_length=40, null=True, verbose_name='local_trabalho')),
                ('escolaridade', models.CharField(max_length=30, null=True, verbose_name='escolaridade')),
                ('pessoa_convite', models.CharField(max_length=30, null=True, verbose_name='pessoa_convite')),
                ('ano_participacao', models.IntegerField(null=True, verbose_name='ano_participacao')),
                ('equipes_trab', models.CharField(blank=True, max_length=70, null=True, verbose_name='equipes_trab')),
                ('qtd_participacoes', models.IntegerField(null=True, verbose_name='qtd_participacoes')),
            ],
        ),
        migrations.CreateModel(
            name='Encontrista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_apelido', models.CharField(max_length=60, verbose_name='nome_apelido')),
                ('possui_automovel', models.CharField(max_length=5, verbose_name='possui_automovel')),
                ('nome_escola', models.CharField(max_length=60, verbose_name='nome_escola')),
                ('possui_probsaude', models.CharField(max_length=5, verbose_name='possui_probsaude')),
                ('nome_probsaude', models.CharField(max_length=60, verbose_name='nome_probsaude')),
                ('pessoas_moradia', models.CharField(max_length=60, verbose_name='pessoas_moradia')),
                ('telefones_urgencia', models.CharField(max_length=40, verbose_name='telefones_urgencia')),
                ('pessoa_convite', models.CharField(max_length=40, verbose_name='pessoa_convite')),
                ('telefone_pessoa_convite', models.CharField(max_length=40, verbose_name='telefone_pessoa_convite')),
                ('pessoas_participando', models.CharField(max_length=5, verbose_name='pessoas_participando')),
                ('nome_pessoas_participando', models.CharField(max_length=60, verbose_name='nome_pessoas_participando')),
                ('nome', models.CharField(max_length=60, verbose_name='nome')),
                ('religiao', models.CharField(max_length=30, verbose_name='religiao')),
                ('frequenta_igreja', models.CharField(max_length=5, verbose_name='frequenta_igreja')),
                ('nome_pai', models.CharField(max_length=60, verbose_name='nome_pai')),
                ('religiao_pai', models.CharField(max_length=30, verbose_name='religiao_pai')),
                ('nome_mae', models.CharField(max_length=60, verbose_name='nome_mae')),
                ('religiao_mae', models.CharField(max_length=60, verbose_name='religiao_mae')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('facebook', models.EmailField(max_length=50, verbose_name='facebook')),
                ('naturalidade', models.CharField(max_length=40, verbose_name='naturalidade')),
                ('cpf', models.CharField(max_length=15, null=True, unique=True, verbose_name='cpf')),
                ('celular', models.CharField(default='', editable=False, max_length=15, verbose_name='celular')),
                ('data_nascimento', models.DateField(null=True, verbose_name='data_nascimento')),
                ('frequentando_igreja', models.CharField(max_length=5, null=True, verbose_name='frequentando_igreja')),
                ('nome_igreja', models.CharField(blank=True, max_length=50, null=True)),
                ('cep', models.CharField(max_length=10, null=True, verbose_name='cep')),
                ('logradouro', models.CharField(max_length=40, null=True, verbose_name='rua')),
                ('numero', models.IntegerField(null=True, verbose_name='numero')),
                ('complemento', models.CharField(max_length=60, null=True, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=25, verbose_name='bairro')),
                ('estado', models.CharField(max_length=4, null=True, verbose_name='estados')),
                ('cidade', models.CharField(max_length=30, null=True, verbose_name='idades')),
                ('local_trabalho', models.CharField(max_length=40, null=True, verbose_name='local_trabalho')),
                ('endereco_trabalho', models.CharField(max_length=60, null=True, verbose_name='endereco_trabalho')),
                ('telefone_trabalho', models.CharField(max_length=20, null=True, verbose_name='telefone_trabalho')),
                ('desejo_participacao', models.CharField(blank=True, max_length=150, null=True, verbose_name='desejo_participacao')),
                ('pergunta_jesus', models.CharField(blank=True, max_length=150, null=True, verbose_name='pergunta_jesus')),
                ('nome_facebook', models.CharField(blank=True, max_length=150, null=True, verbose_name='nome_facebook')),
                ('nome_instagram', models.CharField(blank=True, max_length=150, null=True, verbose_name='nome_instagram')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipe', models.CharField(max_length=40, verbose_name='nome_equipe')),
                ('qtd_participantes', models.IntegerField(null=True, verbose_name='qtd_participantes')),
                ('nome_casal_ligacao', models.CharField(max_length=40, verbose_name='nome_casal_ligacao')),
                ('encontreiros', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encontreiros', to='core.Encontreiro')),
                ('nome_coordenador', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordenador', to='core.Encontreiro')),
            ],
        ),
        migrations.CreateModel(
            name='Circulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_circulo', models.CharField(max_length=40, verbose_name='nome_circulo')),
                ('qtd_participantes', models.IntegerField(null=True, verbose_name='qtd_participantes')),
                ('cor_equipe', models.CharField(max_length=20, verbose_name='cor_equipe')),
                ('encontristas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Encontrista')),
                ('lider_circulo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Encontreiro')),
            ],
        ),
    ]
