# Generated by Django 2.2.6 on 2019-10-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encontrista',
            name='frequentando_igreja',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='nome_facebook',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='nome_igreja',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='nome_instagram',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='telefone_trabalho',
        ),
        migrations.AddField(
            model_name='encontreiro',
            name='curso',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='curso'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='religiao_mae',
            field=models.CharField(max_length=30, verbose_name='religiao_mae'),
        ),
    ]
