# Generated by Django 2.2.6 on 2019-10-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encontreiro',
            old_name='complemento',
            new_name='complemento_encontreiro',
        ),
        migrations.RenameField(
            model_name='encontreiro',
            old_name='numero',
            new_name='numero_encontreiro',
        ),
        migrations.RemoveField(
            model_name='encontreiro',
            name='ano_participacao',
        ),
        migrations.RemoveField(
            model_name='encontreiro',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='encontreiro',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='encontreiro',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='encontreiro',
            name='equipes_trab',
        ),
        migrations.RemoveField(
            model_name='encontreiro',
            name='escolaridade',
        ),
        migrations.RemoveField(
            model_name='encontreiro',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='encontreiro',
            name='frequentando_igreja',
        ),
        migrations.RemoveField(
            model_name='encontreiro',
            name='local_trabalho',
        ),
        migrations.RemoveField(
            model_name='encontreiro',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='encontreiro',
            name='naturalidade',
        ),
        migrations.RemoveField(
            model_name='encontreiro',
            name='nome_igreja',
        ),
        migrations.RemoveField(
            model_name='encontreiro',
            name='pessoa_convite',
        ),
        migrations.RemoveField(
            model_name='encontreiro',
            name='qtd_participacoes',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='frequentando_igreja',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='nome_facebook',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='nome_igreja',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='nome_instagram',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='telefone_trabalho',
        ),
        migrations.AddField(
            model_name='encontreiro',
            name='bairro_encontreiro',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='encontreiro',
            name='cep_encontreiro',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encontreiro',
            name='cidade_encontreiro',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='encontreiro',
            name='estado_civil',
            field=models.CharField(max_length=40, null=True, verbose_name='estado_civil'),
        ),
        migrations.AddField(
            model_name='encontreiro',
            name='estado_encontreiro',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='encontreiro',
            name='logradouro_encontreiro',
            field=models.CharField(max_length=40, null=True, verbose_name='logradouro'),
        ),
        migrations.AddField(
            model_name='encontreiro',
            name='naturalidade_encontreiro',
            field=models.CharField(max_length=40, null=True, verbose_name='naturalidade'),
        ),
        migrations.AddField(
            model_name='encontrista',
            name='estado_civil',
            field=models.CharField(default='', max_length=40, verbose_name='estado_civil'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='celular',
            field=models.CharField(max_length=15, null=True, verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='data_nascimento',
            field=models.DateField(null=True, verbose_name='data nascimento'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='email',
            field=models.EmailField(max_length=50, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='facebook',
            field=models.CharField(max_length=50, null=True, verbose_name='facebook'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='religiao_mae',
            field=models.CharField(max_length=30, verbose_name='religiao_mae'),
        ),
    ]
