# Generated by Django 2.2.6 on 2019-10-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191024_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='encontreiro',
            name='estado_civil',
            field=models.CharField(default='', max_length=40, verbose_name='estado_civil'),
        ),
        migrations.AddField(
            model_name='encontrista',
            name='estado_civil',
            field=models.CharField(default='', max_length=40, verbose_name='estado_civil'),
        ),
    ]
