# Generated by Django 2.2.6 on 2019-10-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191027_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='encontreiro',
            name='frequentando_igreja_enc',
            field=models.CharField(max_length=5, null=True, verbose_name='frequentando igreja'),
        ),
        migrations.AddField(
            model_name='encontreiro',
            name='nome_igreja',
            field=models.CharField(max_length=50, null=True, verbose_name='nome da igreja'),
        ),
    ]
