# Generated by Django 2.2.6 on 2019-10-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191027_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='encontreiro',
            name='escolaridade_enc',
            field=models.CharField(max_length=30, null=True, verbose_name='escolaridade'),
        ),
        migrations.AddField(
            model_name='encontreiro',
            name='local_trabalho_enc',
            field=models.CharField(max_length=40, null=True, verbose_name='local de trabalho'),
        ),
    ]
