# Generated by Django 2.2.6 on 2019-10-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191027_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='encontreiro',
            name='curso_encontreiro',
            field=models.CharField(max_length=70, null=True, verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='encontreiro',
            name='equipes_trab',
            field=models.CharField(max_length=70, null=True, verbose_name='equipes_que trabalhou'),
        ),
        migrations.AddField(
            model_name='encontreiro',
            name='qtd_participacoes',
            field=models.IntegerField(null=True, verbose_name='Quantidade de participações'),
        ),
    ]
