# Generated by Django 2.2.6 on 2019-10-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191027_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encontrista',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='pessoa_convite',
        ),
        migrations.AddField(
            model_name='encontrista',
            name='data_nascimento_enc',
            field=models.DateField(null=True, verbose_name='data nascimento'),
        ),
        migrations.AddField(
            model_name='encontrista',
            name='pessoa_convite_enct',
            field=models.CharField(max_length=40, null=True, verbose_name='padrinho ou madrinha'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='equipes_trab',
            field=models.CharField(max_length=70, null=True, verbose_name='equipes que trabalhou'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='bairro',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='celular',
            field=models.CharField(default='', editable=False, max_length=15, null=True, verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='cidade',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='desejo_participacao',
            field=models.CharField(max_length=150, null=True, verbose_name='desejo participacao'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='email',
            field=models.EmailField(max_length=50, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='endereco_trabalho',
            field=models.CharField(max_length=60, null=True, verbose_name='endereco trabalho'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='estado',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='estado_civil',
            field=models.CharField(max_length=40, null=True, verbose_name='estado_civil'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='facebook',
            field=models.EmailField(max_length=50, null=True, verbose_name='facebook'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='frequenta_igreja',
            field=models.CharField(max_length=5, null=True, verbose_name='frequenta_igreja'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='local_trabalho',
            field=models.CharField(max_length=40, null=True, verbose_name='local trabalho'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='naturalidade',
            field=models.CharField(max_length=40, null=True, verbose_name='naturalidade'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='nome',
            field=models.CharField(max_length=60, null=True, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='nome_apelido',
            field=models.CharField(max_length=60, null=True, verbose_name='nome apelido'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='nome_escola',
            field=models.CharField(max_length=60, null=True, verbose_name='nome escola'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='nome_mae',
            field=models.CharField(max_length=60, null=True, verbose_name='nome_mae'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='nome_pai',
            field=models.CharField(max_length=60, null=True, verbose_name='nome_pai'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='nome_pessoas_participando',
            field=models.CharField(max_length=60, null=True, verbose_name='nome_pessoas_participando'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='nome_probsaude',
            field=models.CharField(max_length=60, null=True, verbose_name='nome probsaude'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='pergunta_jesus',
            field=models.CharField(max_length=150, null=True, verbose_name='Jesus pra você'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='pessoas_moradia',
            field=models.CharField(max_length=60, null=True, verbose_name='pessoas moradia'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='pessoas_participando',
            field=models.CharField(max_length=5, null=True, verbose_name='pessoas_participando'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='possui_automovel',
            field=models.CharField(max_length=5, null=True, verbose_name='possui automovel'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='possui_probsaude',
            field=models.CharField(max_length=5, null=True, verbose_name='possui probsaude'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='religiao',
            field=models.CharField(max_length=30, null=True, verbose_name='religiao'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='religiao_mae',
            field=models.CharField(max_length=30, null=True, verbose_name='religiao_mae'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='religiao_pai',
            field=models.CharField(max_length=30, null=True, verbose_name='religiao_pai'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='telefone_pessoa_convite',
            field=models.CharField(max_length=40, null=True, verbose_name='telefone_pessoa_convite'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='telefones_urgencia',
            field=models.CharField(max_length=40, null=True, verbose_name='telefones urgencia'),
        ),
    ]
