# Generated by Django 2.2.6 on 2019-10-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191027_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encontrista',
            name='desejo_participacao',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='endereco_trabalho',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='frequenta_igreja',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='local_trabalho',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='nome_escola',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='nome_mae',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='nome_pai',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='nome_pessoas_participando',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='nome_probsaude',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='pergunta_jesus',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='pessoa_convite_enct',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='pessoas_moradia',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='pessoas_participando',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='possui_automovel',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='possui_probsaude',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='religiao',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='religiao_mae',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='religiao_pai',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='telefone_pessoa_convite',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='telefones_urgencia',
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='celular',
            field=models.CharField(max_length=15, null=True, verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='facebook',
            field=models.CharField(max_length=50, null=True, verbose_name='facebook'),
        ),
    ]
