# Generated by Django 2.2.6 on 2019-10-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191027_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encontrista',
            name='bairro',
            field=models.CharField(max_length=25, null=True, verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='cidade',
            field=models.CharField(max_length=30, null=True, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='estado',
            field=models.CharField(max_length=4, null=True, verbose_name='estado'),
        ),
    ]
