# Generated by Django 2.2.6 on 2019-10-27 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191027_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encontrista',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='email',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='naturalidade',
        ),
        migrations.RemoveField(
            model_name='encontrista',
            name='numero',
        ),
    ]
