# Generated by Django 2.2.6 on 2019-10-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191027_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='encontrista',
            name='cep',
            field=models.CharField(max_length=10, null=True, verbose_name='cep'),
        ),
        migrations.AddField(
            model_name='encontrista',
            name='estado_civil',
            field=models.CharField(max_length=40, null=True, verbose_name='estado_civil'),
        ),
    ]
