# Generated by Django 2.2.6 on 2019-10-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191027_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='encontrista',
            name='bairro',
            field=models.CharField(max_length=25, null=True, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='encontrista',
            name='cidade',
            field=models.CharField(max_length=30, null=True, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='encontrista',
            name='complemento',
            field=models.CharField(max_length=60, null=True, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='encontrista',
            name='email',
            field=models.EmailField(max_length=50, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='encontrista',
            name='estado',
            field=models.CharField(max_length=4, null=True, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='encontrista',
            name='facebook',
            field=models.CharField(max_length=50, null=True, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='encontrista',
            name='logradouro',
            field=models.CharField(max_length=40, null=True, verbose_name='rua'),
        ),
        migrations.AddField(
            model_name='encontrista',
            name='naturalidade',
            field=models.CharField(max_length=40, null=True, verbose_name='naturalidade'),
        ),
        migrations.AddField(
            model_name='encontrista',
            name='numero',
            field=models.IntegerField(null=True, verbose_name='numero'),
        ),
    ]
