# Generated by Django 2.2.6 on 2019-10-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191027_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='encontrista',
            name='frequenta_igreja',
            field=models.CharField(max_length=5, null=True, verbose_name='frequenta_igreja'),
        ),
        migrations.AddField(
            model_name='encontrista',
            name='nome_mae',
            field=models.CharField(max_length=60, null=True, verbose_name='nome_mae'),
        ),
        migrations.AddField(
            model_name='encontrista',
            name='nome_pai',
            field=models.CharField(max_length=60, null=True, verbose_name='nome_pai'),
        ),
        migrations.AddField(
            model_name='encontrista',
            name='religiao',
            field=models.CharField(max_length=30, null=True, verbose_name='religiao'),
        ),
        migrations.AddField(
            model_name='encontrista',
            name='religiao_mae',
            field=models.CharField(max_length=30, null=True, verbose_name='religiao_mae'),
        ),
        migrations.AddField(
            model_name='encontrista',
            name='religiao_pai',
            field=models.CharField(max_length=30, null=True, verbose_name='religiao_pai'),
        ),
    ]
