# Generated by Django 2.2.6 on 2019-10-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20191027_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encontrista',
            name='desejo_participacao',
            field=models.TextField(null=True, verbose_name='desejo participacao'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='pergunta_jesus',
            field=models.TextField(null=True, verbose_name='Jesus pra você'),
        ),
    ]
