# Generated by Django 2.2.6 on 2019-10-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20191027_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='encontreiro',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Inscrito em'),
        ),
        migrations.AddField(
            model_name='encontrista',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Inscrito em'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='ano_participacao',
            field=models.IntegerField(null=True, verbose_name='Ano de participação'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='bairro_encontreiro',
            field=models.CharField(max_length=25, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='celular',
            field=models.CharField(max_length=15, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='cep_encontreiro',
            field=models.CharField(max_length=11, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='cidade_encontreiro',
            field=models.CharField(max_length=30, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='complemento_encontreiro',
            field=models.CharField(max_length=60, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='cpf',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='curso_encontreiro',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='data_nascimento',
            field=models.DateField(null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='email',
            field=models.EmailField(max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='equipes_trab',
            field=models.CharField(max_length=70, null=True, verbose_name='Equipes que já trabalhou'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='escolaridade_enc',
            field=models.CharField(max_length=30, null=True, verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='estado_civil',
            field=models.CharField(max_length=40, null=True, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='estado_encontreiro',
            field=models.CharField(max_length=26, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='facebook',
            field=models.CharField(max_length=50, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='frequentando_igreja_enc',
            field=models.CharField(max_length=5, null=True, verbose_name='Está frequentando a igreja?'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='local_trabalho_enc',
            field=models.CharField(max_length=40, null=True, verbose_name='Local de trabalho'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='logradouro_encontreiro',
            field=models.CharField(max_length=40, null=True, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='naturalidade_encontreiro',
            field=models.CharField(max_length=40, null=True, verbose_name='Naturalidade'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='nome',
            field=models.CharField(max_length=60, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='nome_igreja',
            field=models.CharField(max_length=50, null=True, verbose_name='Nome da igreja'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='numero_encontreiro',
            field=models.IntegerField(null=True, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='encontreiro',
            name='pessoa_convite_enc',
            field=models.CharField(max_length=30, null=True, verbose_name='Padrinho ou madrinha'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='bairro',
            field=models.CharField(max_length=25, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='celular',
            field=models.CharField(max_length=15, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='cep',
            field=models.CharField(max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='cidade',
            field=models.CharField(max_length=30, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='complemento',
            field=models.CharField(max_length=60, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='cpf',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='curso',
            field=models.CharField(max_length=50, null=True, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='data_nascimento_enc',
            field=models.DateField(null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='desejo_participacao',
            field=models.TextField(null=True, verbose_name='Porque deseja participar do programa?'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='email',
            field=models.EmailField(max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='escolaridade',
            field=models.CharField(max_length=40, null=True, verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='estado',
            field=models.CharField(max_length=4, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='estado_civil',
            field=models.CharField(max_length=40, null=True, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='facebook',
            field=models.CharField(max_length=50, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='frequenta_igreja',
            field=models.CharField(max_length=5, null=True, verbose_name='Está frequentando alguma igreja?'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='local_trabalho',
            field=models.CharField(max_length=40, null=True, verbose_name='Local de trabalho'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='logradouro',
            field=models.CharField(max_length=40, null=True, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='naturalidade',
            field=models.CharField(max_length=40, null=True, verbose_name='Naturalidade'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='nome_apelido',
            field=models.CharField(max_length=60, null=True, verbose_name='Nome apelido'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='nome_escola',
            field=models.CharField(max_length=60, null=True, verbose_name='Nome da escola'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='nome_mae',
            field=models.CharField(max_length=60, null=True, verbose_name='Nome da mãe'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='nome_pai',
            field=models.CharField(max_length=60, null=True, verbose_name='Nome do pai'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='nome_pessoas_participando',
            field=models.CharField(max_length=60, null=True, verbose_name='Nome das pessoas'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='nome_probsaude',
            field=models.CharField(max_length=60, null=True, verbose_name='Qual problema de saúde'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='numero',
            field=models.IntegerField(null=True, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='pergunta_jesus',
            field=models.TextField(null=True, verbose_name='Quem é Jesus para você?'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='pessoa_convite_enct',
            field=models.CharField(max_length=40, null=True, verbose_name='Quem o convidou?'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='pessoas_moradia',
            field=models.CharField(max_length=60, null=True, verbose_name='Quem mora na mesma residência'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='pessoas_participando',
            field=models.CharField(max_length=5, null=True, verbose_name='Algum conhecido participando do programa?'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='possui_automovel',
            field=models.CharField(max_length=5, null=True, verbose_name='Possui automóvel?'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='possui_probsaude',
            field=models.CharField(max_length=5, null=True, verbose_name='Possui algum problema de saúde?'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='religiao',
            field=models.CharField(max_length=30, null=True, verbose_name='Religião'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='religiao_mae',
            field=models.CharField(max_length=30, null=True, verbose_name='Religião da mãe'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='religiao_pai',
            field=models.CharField(max_length=30, null=True, verbose_name='Religião do pai'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='telefone_pessoa_convite',
            field=models.CharField(max_length=40, null=True, verbose_name='Telefone do encontreiro'),
        ),
        migrations.AlterField(
            model_name='encontrista',
            name='telefones_urgencia',
            field=models.CharField(max_length=40, null=True, verbose_name='Telefones para urgência'),
        ),
    ]
