# Generated by Django 2.2.6 on 2019-11-08 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20191107_2107'),
        ('core', '0019_auto_20191028_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='encontreiro',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.Order', verbose_name='Pagamento'),
        ),
        migrations.AddField(
            model_name='encontrista',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.Order', verbose_name='Pagamento'),
        ),
    ]
