# Generated by Django 2.2.6 on 2019-11-06 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('checkout', '0002_auto_20191105_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='inscricao',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart_key', 'inscricao')},
        ),
    ]
