# Generated by Django 2.2.6 on 2019-11-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20191106_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('pagseguro', 'PagSeguro')], default='desposit', max_length=20, verbose_name='Opção de Pagamento'),
        ),
    ]
