# Generated by Django 2.2.6 on 2019-11-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20191107_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart_key',
            field=models.CharField(db_index=True, max_length=40, null=True, verbose_name='Chave do Carrinho'),
        ),
    ]
